export const GET_USER_LOCATION = 'GET_USER_LOCATION' 
export const SET_USER_GEOLOCATION = 'SET_USER_GEOLOCATION' 
export const GET_PLACES_INFORMATION = 'GET_PLACES_INFORMATION'
export const CLEAR_PLACES = 'CLEAR_PLACES'